

```{r}
library(dplyr)
library(xlsx)

# Load the dataset from an Excel file
data <- read.xlsx('hook_data.xlsx', sheetIndex = 1)


# Function to replace outliers with 0
replace_outliers <- function(x) {
  Q1 <- quantile(x, 0.25, na.rm = TRUE)
  Q3 <- quantile(x, 0.75, na.rm = TRUE)
  IQR <- Q3 - Q1
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  x[x < lower_bound | x > upper_bound] <- 0
  return(x)
}

# Apply the function to each column
cleaned_data <- data %>% mutate(across(c(male_x1, male_x2, female_x1, female_x2), replace_outliers))

```


```{r}
# drop row with 0

X1 <- cbind(cleaned_data$male_x1, cleaned_data$male_x2)
X2 <- cbind(cleaned_data$female_x1, cleaned_data$female_x2)

#drop rows with 0
X1 <- X1[apply(X1, 1, function(x) all(x != 0)), ]
X2 <- X2[apply(X2, 1, function(x) all(x != 0)), ]

```


```{r}


nl <- c(nrow(X1), nrow(X2))
p <- ncol(X1)


X <- rbind(X1, X2)
group <- c(rep(1, nl[1]), rep(2, nl[2]))
group <- as.factor(group)
fit <- manova(X ~ group) 
summary(fit, 'Wilks')

summary.aov(fit)

```



```{r}

peanuts <- read.table('T6-17.dat')
head(peanuts)
#make V1 and V2 factors
peanuts$V1 <- as.factor(peanuts$V1)
peanuts$V2 <- as.factor(peanuts$V2)

attach(peanuts)
X <- cbind(V3, V4, V5) 

#Fit two-way MANOVA
fit1 <- manova(X ~ V1*V2)
(summary1 <- summary(fit1, test = 'Wilks'))



```

```{r}
#To conduct separate TWO WAY ANOVA's
X <- X[,2]

fit2 <- aov(X ~ V1*V2)
summary(aov(X ~ V1*V2))
```

```{r}

fit2 <- aov(X ~ V1*V2)
summary(aov(X ~ V1*V2))
# Load the DescTools package
library(DescTools)

post_hoc_result <- PostHocTest(fit2, method = "bonferroni", control = "independent_var")

# Print the results
print(post_hoc_result)

```

